[Common]
Login=0
ProxyEnable=0
CertPassword=0
NewsEnable=0
SoundEnable=0
EventsEnable=0
MailEnable=0
FTPEnable=0
SignalEnable=0

[Charts]
MaxBars=5000
PrintColor=0
ShowTickValue=0
ShowOHLC=0
ShowDataWindow=0
ShowBidLine=1
ShowAskLine=0
ShowLastLine=0
ShowPeriodSeparator=0
ShowGrid=0
ShowVolume=0
ShowDescription=0

[Experts]
AllowLiveTrading=1
AllowDllImport=1
DisableAfterAccountChanged=0
DisableAfterProfileChanged=0

[Startup]
; Automatically run our socket bridge on startup
Script=jfx_socket_bridge
