import React, { useState, useRef, useEffect } from 'react';
import CreateArea from './notes/CreateArea';
import NoteCard from './notes/NoteCard';
import NoteEditor from './notes/NoteEditor';
import Sidebar from './notes/Sidebar';
import { Note as KeepNote, NoteColor, SidebarSection } from './notes/types';
import { Note as AppNote, Goal, UserProfile } from '../types';
import { Search, Menu, RefreshCw, Grid, Settings, Trash2, Archive, Lightbulb, ChevronLeft } from 'lucide-react';

interface NotesProps {
  isDarkMode: boolean;
  notes: AppNote[];
  goals: Goal[];
  onAddNote: (note: any) => Promise<any>;
  onUpdateNote: (note: any) => Promise<void>;
  onDeleteNote: (id: string) => Promise<void>;
  onRestoreNote: (id: string) => Promise<void>;
  onUpdateGoal: (goal: Goal) => Promise<void>;
  userProfile?: UserProfile | null;
  onViewChange: (view: string) => void;
}

const Notes: React.FC<NotesProps> = ({ 
  isDarkMode, 
  notes: appNotes, 
  onAddNote, 
  onUpdateNote, 
  onDeleteNote, 
  onRestoreNote,
  userProfile, 
  onViewChange 
}) => {
  const [selectedNoteId, setSelectedNoteId] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [draggedNote, setDraggedNote] = useState<KeepNote | null>(null);
  const [currentSection, setCurrentSection] = useState<SidebarSection>('NOTES');
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);
  
  // Canvas Size State
  const [canvasWidth, setCanvasWidth] = useState(700);
  const [canvasHeight, setCanvasHeight] = useState(0); 
  const [isResizing, setIsResizing] = useState(false);
  const resizeRef = useRef<{ startX: number; startY: number; startWidth: number; startHeight: number } | null>(null);

  // Map AppNote to KeepNote
  const notes: KeepNote[] = appNotes.map(n => ({
    id: n.id,
    title: n.title,
    content: n.content,
    isPinned: !!n.isPinned,
    isArchived: (n as any).isArchived || false,
    isTrashed: (n as any).isTrashed || false,
    color: (n.color?.toUpperCase() as NoteColor) || NoteColor.DEFAULT,
    labels: n.tags || [],
    createdAt: new Date(n.date).getTime(),
    updatedAt: new Date(n.date).getTime(),
    isList: (n as any).isList || false,
    listItems: (n as any).listItems || [],
    image: (n as any).image,
    tableData: (n as any).tableData,
  }));

  const selectedNote = notes.find(n => n.id === selectedNoteId) || null;

  const handleCreateNote = async (newNoteData: Omit<KeepNote, 'id' | 'createdAt' | 'updatedAt' | 'isArchived' | 'isTrashed' | 'labels'>) => {
    const newNote: Partial<AppNote> = {
      title: newNoteData.title,
      content: newNoteData.content,
      isPinned: newNoteData.isPinned,
      color: newNoteData.color.toLowerCase() as any,
      tags: [],
      date: new Date().toISOString(),
    };
    
    // Add extra fields for the new notebook
    (newNote as any).isList = newNoteData.isList;
    (newNote as any).listItems = newNoteData.listItems;
    (newNote as any).image = newNoteData.image;
    (newNote as any).tableData = newNoteData.tableData;

    try {
      const added = await onAddNote(newNote);
      if (added) {
        setSelectedNoteId(added.id);
      }
    } catch (e) {
      console.error("Failed to create note", e);
    }
  };

  const handleUpdateKeepNote = (updatedNote: KeepNote) => {
    const update: Partial<AppNote> & { id: string } = {
      id: updatedNote.id,
      title: updatedNote.title,
      content: updatedNote.content,
      isPinned: updatedNote.isPinned,
      color: updatedNote.color.toLowerCase() as any,
      tags: updatedNote.labels,
      date: new Date(updatedNote.updatedAt).toISOString(),
    };
    
    // Add extra fields
    (update as any).isArchived = updatedNote.isArchived;
    (update as any).isTrashed = updatedNote.isTrashed;
    (update as any).isList = updatedNote.isList;
    (update as any).listItems = updatedNote.listItems;
    (update as any).image = updatedNote.image;
    (update as any).tableData = updatedNote.tableData;

    onUpdateNote(update);
  };

  const handlePinNote = (e: React.MouseEvent, note: KeepNote) => {
    e.stopPropagation();
    handleUpdateKeepNote({ ...note, isPinned: !note.isPinned });
  };

  const handleArchiveNote = (e: React.MouseEvent, note: KeepNote) => {
    e.stopPropagation();
    const nextArchived = !note.isArchived;
    handleUpdateKeepNote({ ...note, isArchived: nextArchived });
    if (selectedNoteId === note.id) setSelectedNoteId(null);
  };
  
  const handleDeleteNote = (id: string) => {
      onDeleteNote(id);
      if (selectedNoteId === id) setSelectedNoteId(null);
  };

  const handleRestoreNote = (e: React.MouseEvent, note: KeepNote) => {
      e.stopPropagation();
      onRestoreNote(note.id);
  };

  const handleDuplicateNote = (note: KeepNote) => {
      const duplicate = {
          ...note,
          id: '', // Will be generated by DB
          title: note.title + " (Copy)",
          updatedAt: Date.now(),
      };
      handleCreateNote(duplicate);
  };

  const handleDropNote = (targetNote: KeepNote) => {
    if (!draggedNote || draggedNote.id === targetNote.id) return;
    // Reordering logic would go here if we had a position field in DB
    setDraggedNote(null);
  };

  // Resize Handlers
  const startResizing = (e: React.MouseEvent) => {
    e.preventDefault();
    setIsResizing(true);
    resizeRef.current = {
      startX: e.clientX,
      startY: e.clientY,
      startWidth: canvasWidth,
      startHeight: canvasHeight || 0,
    };
  };

  useEffect(() => {
    const handleMouseMove = (e: MouseEvent) => {
      if (!isResizing || !resizeRef.current) return;
      const deltaX = e.clientX - resizeRef.current.startX;
      const deltaY = e.clientY - resizeRef.current.startY;
      const newWidth = Math.max(400, Math.min(2000, resizeRef.current.startWidth + deltaX));
      const newHeight = Math.max(0, resizeRef.current.startHeight + deltaY);
      setCanvasWidth(newWidth);
      setCanvasHeight(newHeight);
    };

    const handleMouseUp = () => {
      setIsResizing(false);
      resizeRef.current = null;
    };

    if (isResizing) {
      window.addEventListener('mousemove', handleMouseMove);
      window.addEventListener('mouseup', handleMouseUp);
    }

    return () => {
      window.removeEventListener('mousemove', handleMouseMove);
      window.removeEventListener('mouseup', handleMouseUp);
    };
  }, [isResizing]);

  const filteredNotes = notes.filter(note => {
    const matchesSearch = note.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
                          note.content.toLowerCase().includes(searchQuery.toLowerCase()) ||
                          note.listItems?.some(item => item.text.toLowerCase().includes(searchQuery.toLowerCase()));
    
    if (currentSection === 'ARCHIVE') return note.isArchived && !note.isTrashed && matchesSearch;
    if (currentSection === 'TRASH') return note.isTrashed && matchesSearch;
    return !note.isArchived && !note.isTrashed && matchesSearch;
  });

  const pinnedNotes = filteredNotes.filter(n => n.isPinned);
  const otherNotes = filteredNotes.filter(n => !n.isPinned);

  return (
    <div className={`flex flex-col h-full w-full font-sans overflow-hidden ${isResizing ? 'cursor-nwse-resize select-none' : ''}`} style={{ backgroundColor: 'var(--note-default-bg)', color: 'var(--notebook-text)' }}>
      {/* Header */}
      <header className="flex items-center justify-between px-6 py-2 border-b h-16 shrink-0 z-20" style={{ backgroundColor: 'var(--note-default-bg)', borderColor: 'var(--notebook-divider)' }}>
        <div className="flex items-center gap-4">
          <button 
            onClick={() => setIsSidebarOpen(!isSidebarOpen)}
            aria-label={isSidebarOpen ? "Collapse sidebar" : "Expand sidebar"}
            aria-expanded={isSidebarOpen}
            className={`p-2 rounded-lg transition-colors hover:bg-[var(--notebook-hover)] text-[var(--notebook-muted)]`}
          >
            <Menu className="w-6 h-6" />
          </button>
          <div className="flex items-center gap-2 cursor-pointer" onClick={() => setSelectedNoteId(null)}>
            <div className="p-1.5 rounded-lg bg-indigo-600 text-white shadow-lg shadow-indigo-500/20">
              <Lightbulb className="w-6 h-6" />
            </div>
            <span className="text-xl font-bold tracking-tight">Keep Notebook</span>
          </div>
        </div>

        <div className="flex-1 max-w-[720px] mx-8">
          <div className={`relative flex items-center rounded-xl transition-all group bg-[var(--notebook-hover)] focus-within:bg-[var(--note-default-bg)] focus-within:ring-1 focus-within:ring-[var(--notebook-divider)]`}>
            <div className={`p-3 text-[var(--notebook-muted)] group-focus-within:text-indigo-500`}>
              <Search className="w-5 h-5" />
            </div>
            <input 
              id="notes-search-input"
              name="search"
              aria-label="Search your notes"
              type="text" 
              placeholder="Search your notes..." 
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full bg-transparent outline-none py-3 text-base placeholder:opacity-50"
              style={{ color: 'var(--notebook-text)' }}
            />
          </div>
        </div>

        <div className="flex items-center gap-2">
          <HeaderIcon icon={<RefreshCw className="w-5 h-5" />} title="Refresh" isDarkMode={isDarkMode} />
          <HeaderIcon icon={<Settings className="w-5 h-5" />} title="Settings" isDarkMode={isDarkMode} onClick={() => onViewChange('settings')} />
        </div>
      </header>

      {/* Main Content Area */}
      <div className="flex flex-1 overflow-hidden relative">
        <Sidebar 
            activeSection={currentSection} 
            onSectionChange={setCurrentSection} 
            isOpen={isSidebarOpen} 
        />
        
        <div className={`flex flex-1 overflow-hidden transition-all duration-300`}>
            {/* Left Side: Scrollable Notes List */}
            <aside className="w-[380px] flex flex-col border-r shrink-0 overflow-y-auto custom-scrollbar transition-all duration-300" style={{ backgroundColor: 'var(--note-default-bg)', borderColor: 'var(--notebook-divider)' }}>
                <div className="p-4 space-y-4">
                    {pinnedNotes.length > 0 && (
                        <div className="mb-8">
                            <h2 className="text-[0.65rem] font-black tracking-widest mb-4 uppercase pl-2 opacity-50">Pinned</h2>
                            <div className="flex flex-col gap-3">
                                {pinnedNotes.map(note => (
                                    <NoteCard 
                                        key={note.id} 
                                        note={note} 
                                        isDragging={draggedNote?.id === note.id}
                                        onClick={(n) => setSelectedNoteId(n.id)}
                                        onPin={handlePinNote}
                                        onArchive={handleArchiveNote}
                                        onDelete={(e, n) => { e.stopPropagation(); handleDeleteNote(n.id); }}
                                        onRestore={handleRestoreNote}
                                        onUpdate={handleUpdateKeepNote}
                                        onDragStart={setDraggedNote}
                                        onDragEnd={() => setDraggedNote(null)}
                                        onDrop={handleDropNote}
                                    />
                                ))}
                            </div>
                        </div>
                    )}

                    {(pinnedNotes.length > 0 || otherNotes.length > 0) ? (
                        <div>
                            {pinnedNotes.length > 0 && otherNotes.length > 0 && (
                                <h2 className="text-[0.65rem] font-black tracking-widest mb-4 uppercase pl-2 opacity-50">Others</h2>
                            )}
                            <div className="flex flex-col gap-3">
                                {otherNotes.map(note => (
                                    <NoteCard 
                                        key={note.id} 
                                        note={note} 
                                        isDragging={draggedNote?.id === note.id}
                                        onClick={(n) => setSelectedNoteId(n.id)}
                                        onPin={handlePinNote}
                                        onArchive={handleArchiveNote}
                                        onDelete={(e, n) => { e.stopPropagation(); handleDeleteNote(n.id); }}
                                        onRestore={handleRestoreNote}
                                        onUpdate={handleUpdateKeepNote}
                                        onDragStart={setDraggedNote}
                                        onDragEnd={() => setDraggedNote(null)}
                                        onDrop={handleDropNote}
                                    />
                                ))}
                            </div>
                        </div>
                    ) : (
                        <div className="flex flex-col items-center justify-center py-20 opacity-20">
                            <Lightbulb className="w-16 h-16 mb-4" />
                            <p className="text-sm font-bold uppercase tracking-wider">No notes found</p>
                        </div>
                    )}
                </div>
            </aside>

            {/* Right Side: Workspace Canvas */}
            <main className={`flex-1 overflow-y-auto custom-scrollbar flex flex-col items-center py-12 px-8 relative bg-[var(--note-default-bg)]`}>
              
              <div 
                className={`relative transition-all duration-300 ${isResizing ? 'ring-2 ring-indigo-500/50' : ''}`}
                style={{ 
                  width: `${canvasWidth}px`, 
                  height: canvasHeight > 0 ? `${canvasHeight}px` : 'auto',
                  minWidth: '400px'
                }}
              >
                {selectedNote ? (
                  <div className="w-full flex justify-center animate-in fade-in slide-in-from-bottom-4 duration-500 ease-spring">
                                        <NoteEditor 
                                            note={selectedNote} 
                                            onClose={() => setSelectedNoteId(null)}
                                            onUpdate={handleUpdateKeepNote}
                                            onDelete={handleDeleteNote}
                                            onRestore={onRestoreNote}
                                            onDuplicate={handleDuplicateNote}
                                            canvasWidth={canvasWidth}
                                            setCanvasWidth={setCanvasWidth}
                                        />                  </div>
                ) : (
                  <div className="flex flex-col items-center">
                    <div className="w-full mb-20">
                      <CreateArea 
                        onCreate={handleCreateNote} 
                        canvasWidth={canvasWidth}
                        setCanvasWidth={setCanvasWidth}
                      />
                    </div>

                    <div className={`w-full flex flex-col items-center text-center opacity-10 select-none pointer-events-none mt-12 text-[var(--notebook-text)]`}>
                            <div className="mb-6">
                               <Lightbulb className="w-32 h-32 mx-auto stroke-1" />
                            </div>
                            <h3 className="text-3xl font-black uppercase tracking-tight">Your Ideas Await</h3>
                            <p className="mt-2 text-lg font-medium">Select a note from the list to refine your thoughts</p>
                    </div>
                  </div>
                )}

                {/* Canvas Resize Handle */}
                <div 
                  onMouseDown={startResizing}
                  className={`absolute bottom-0 right-0 w-10 h-10 flex items-center justify-center cursor-nwse-resize z-50 group pointer-events-auto
                    ${isResizing ? 'text-indigo-500' : 'text-zinc-500 opacity-0 group-hover:opacity-100'} 
                    hover:opacity-100 transition-all`}
                  title="Resize canvas"
                >
                  <svg 
                    className="w-6 h-6 rotate-45 transform" 
                    viewBox="0 0 24 24" 
                    fill="none" 
                    stroke="currentColor" 
                    strokeWidth="3" 
                    strokeLinecap="round" 
                    strokeLinejoin="round"
                  >
                    <line x1="16" y1="21" x2="21" y2="16" />
                    <line x1="11" y1="21" x2="21" y2="11" />
                  </svg>
                </div>
              </div>
            </main>
        </div>
      </div>
    </div>
  );
};

const HeaderIcon = ({ icon, title, isDarkMode, onClick }: { icon: React.ReactNode, title: string, isDarkMode: boolean, onClick?: () => void }) => (
    <button 
      onClick={onClick}
      className={`p-2.5 rounded-xl transition-all active:scale-95 hover:bg-[var(--notebook-hover)] text-[var(--notebook-muted)] hover:text-[var(--notebook-text)]`} 
      title={title}
    >
        {icon}
    </button>
);

export default Notes;