import { DailyBias, EASession, Note, Trade, UserProfile } from '../types';

const demoTrade = (trade: Trade): Trade => trade;

export const demoTrades: Trade[] = [
  demoTrade({
    id: 'demo-trade-001',
    pair: 'EURUSD',
    assetType: 'Forex',
    date: '2026-01-05',
    time: '08:12',
    session: 'London',
    direction: 'Long',
    entryPrice: 1.0824,
    exitPrice: 1.0862,
    stopLoss: 1.0809,
    takeProfit: 1.0887,
    lots: 1.2,
    result: 'Win',
    pnl: 180,
    rr: 2.4,
    rating: 5,
    tags: ['London Open', 'Breakout', 'A+ Setup'],
    notes: 'Clean bullish break after the Asian range held. Took partials at 1R and left a runner into the London continuation.',
    tradingMistake: 'Nearly entered before the candle close confirmed the breakout.',
    mindset: 'Patient and focused',
    exitComment: 'Executed the plan without forcing an early exit.',
    emotions: ['Calm', 'Confident'],
    planAdherence: 'Followed Exactly',
    setupId: 'demo-eur-breakout',
    setupName: 'EURUSD London Sweep',
    openTime: '2026-01-05T08:12:00+02:00',
    closeTime: '2026-01-05T10:41:00+02:00',
  }),
  demoTrade({
    id: 'demo-trade-002',
    pair: 'GBPUSD',
    assetType: 'Forex',
    date: '2026-01-09',
    time: '13:26',
    session: 'New York',
    direction: 'Short',
    entryPrice: 1.2735,
    exitPrice: 1.2757,
    stopLoss: 1.2718,
    takeProfit: 1.2704,
    lots: 1.0,
    result: 'Loss',
    pnl: -120,
    rr: 1.8,
    rating: 2,
    tags: ['News Fade', 'Impulse', 'Mistake'],
    notes: 'Reversed too early into a strong news impulse. The setup was valid on paper, but the entry was taken before confirmation.',
    tradingMistake: 'Fought the trend and ignored the higher-time-frame structure.',
    mindset: 'Rushed',
    exitComment: 'Stop was hit quickly; the market kept expanding higher.',
    emotions: ['Impatient', 'Frustrated'],
    planAdherence: 'Minor Deviation',
    openTime: '2026-01-09T13:26:00+02:00',
    closeTime: '2026-01-09T13:58:00+02:00',
  }),
  demoTrade({
    id: 'demo-trade-003',
    pair: 'XAUUSD',
    assetType: 'Commodities',
    date: '2026-01-14',
    time: '09:03',
    session: 'London',
    direction: 'Long',
    entryPrice: 2036.5,
    exitPrice: 2043.1,
    stopLoss: 2034.4,
    takeProfit: 2045.9,
    lots: 0.8,
    result: 'Win',
    pnl: 320,
    rr: 3.1,
    rating: 5,
    tags: ['Liquidity Sweep', 'Gold', 'Momentum'],
    notes: 'Price swept the prior day low and reclaimed the VWAP area. Momentum stayed strong through the London expansion.',
    tradingMistake: 'Could have added on the retest instead of taking the whole position at once.',
    mindset: 'Calm',
    exitComment: 'Scaled out into strength and protected the remainder at breakeven.',
    emotions: ['Calm', 'Bold'],
    planAdherence: 'Followed Exactly',
    openTime: '2026-01-14T09:03:00+02:00',
    closeTime: '2026-01-14T11:27:00+02:00',
  }),
  demoTrade({
    id: 'demo-trade-004',
    pair: 'NAS100',
    assetType: 'Indices',
    date: '2026-01-19',
    time: '15:11',
    session: 'New York',
    direction: 'Short',
    entryPrice: 17214,
    exitPrice: 17212,
    stopLoss: 17240,
    takeProfit: 17170,
    lots: 0.6,
    result: 'BE',
    pnl: 0,
    rr: 1.7,
    rating: 3,
    tags: ['Range Day', 'Partial', 'Learning'],
    notes: 'Took a clean short from resistance, but the session went flat after the initial move. The trade worked conceptually, but there was no follow-through.',
    tradingMistake: 'Moved the stop to breakeven too quickly and clipped the trade before expansion.',
    mindset: 'Cautious',
    exitComment: 'Flat result after the market stalled around the mid-range.',
    emotions: ['Neutral', 'Disciplined'],
    planAdherence: 'Minor Deviation',
    openTime: '2026-01-18T15:11:00+02:00',
    closeTime: '2026-01-18T16:02:00+02:00',
  }),
  demoTrade({
    id: 'demo-trade-005',
    pair: 'USDJPY',
    assetType: 'Forex',
    date: '2026-01-23',
    time: '07:42',
    session: 'Asia',
    direction: 'Long',
    entryPrice: 148.21,
    exitPrice: 147.88,
    stopLoss: 148.05,
    takeProfit: 148.74,
    lots: 1.1,
    result: 'Loss',
    pnl: -90,
    rr: 1.6,
    rating: 2,
    tags: ['Asia Session', 'Reversal', 'Countertrend'],
    notes: 'A small countertrend long failed after Tokyo rejected the high. The trade was lower quality and should have been skipped.',
    tradingMistake: 'Ignored the broader bearish pressure on the 4H chart.',
    mindset: 'Hopeful',
    exitComment: 'Stopped out as the pair rolled over into the London open.',
    emotions: ['Hopeful', 'Annoyed'],
    planAdherence: 'Major Deviation',
    openTime: '2026-01-23T07:42:00+02:00',
    closeTime: '2026-01-23T08:15:00+02:00',
  }),
  demoTrade({
    id: 'demo-trade-006',
    pair: 'EURUSD',
    assetType: 'Forex',
    date: '2026-01-28',
    time: '14:07',
    session: 'New York',
    direction: 'Short',
    entryPrice: 1.0898,
    exitPrice: 1.0851,
    stopLoss: 1.0917,
    takeProfit: 1.0842,
    lots: 1.3,
    result: 'Win',
    pnl: 240,
    rr: 2.5,
    rating: 4,
    tags: ['Trend Day', 'Pullback', 'Execution'],
    notes: 'A good pullback entry in the direction of the dominant trend. Price respected the retest and followed through cleanly.',
    tradingMistake: 'Could have held for a slightly larger target, but the execution was solid.',
    mindset: 'Focused',
    exitComment: 'Booked gains into the late New York session with no hesitation.',
    emotions: ['Focused', 'Satisfied'],
    planAdherence: 'Followed Exactly',
    openTime: '2026-01-28T14:07:00+02:00',
    closeTime: '2026-01-28T16:19:00+02:00',
    setupId: 'demo-eur-breakout',
    setupName: 'EURUSD London Sweep',
  }),
  demoTrade({
    id: 'demo-trade-007',
    pair: 'XAUUSD',
    assetType: 'Commodities',
    date: '2026-02-03',
    time: '08:55',
    session: 'London',
    direction: 'Short',
    entryPrice: 2018.6,
    exitPrice: 2010.9,
    stopLoss: 2021.4,
    takeProfit: 2007.2,
    lots: 0.7,
    result: 'Win',
    pnl: 410,
    rr: 2.8,
    rating: 5,
    tags: ['Sweep', 'Gold', 'High Volatility'],
    notes: 'Excellent short after a failed breakout above the prior session high. The rejection was immediate and the move stayed one-sided.',
    tradingMistake: 'Took profits slightly early before the final acceleration.',
    mindset: 'Sharp',
    exitComment: 'Followed the move into support and protected the bulk of the gain.',
    emotions: ['Sharp', 'Confident'],
    planAdherence: 'Followed Exactly',
    openTime: '2026-02-03T08:55:00+02:00',
    closeTime: '2026-02-03T11:03:00+02:00',
    setupId: 'demo-gold-sweep',
    setupName: 'Gold Sweep Reversal',
  }),
  demoTrade({
    id: 'demo-trade-008',
    pair: 'GBPUSD',
    assetType: 'Forex',
    date: '2026-02-06',
    time: '12:18',
    session: 'London',
    direction: 'Long',
    entryPrice: 1.2654,
    exitPrice: 1.2626,
    stopLoss: 1.2632,
    takeProfit: 1.2689,
    lots: 1.0,
    result: 'Loss',
    pnl: -150,
    rr: 1.9,
    rating: 2,
    tags: ['Failed Breakout', 'Impulse', 'Rule Break'],
    notes: 'The breakout candle was strong, but the follow-through was weak and the rejection came quickly. This was a classic chase entry.',
    tradingMistake: 'Entered too far into the candle and ignored the poor location.',
    mindset: 'FOMO',
    exitComment: 'Stopped out when price slipped back under the breakout zone.',
    emotions: ['Rushed', 'Frustrated'],
    planAdherence: 'Major Deviation',
    openTime: '2026-02-07T12:18:00+02:00',
    closeTime: '2026-02-07T12:56:00+02:00',
  }),
  demoTrade({
    id: 'demo-trade-009',
    pair: 'NAS100',
    assetType: 'Indices',
    date: '2026-02-12',
    time: '09:24',
    session: 'London',
    direction: 'Long',
    entryPrice: 17480,
    exitPrice: 17531,
    stopLoss: 17442,
    takeProfit: 17568,
    lots: 0.5,
    result: 'Win',
    pnl: 260,
    rr: 2.2,
    rating: 4,
    tags: ['Momentum', 'Asia Range', 'Cluster'],
    notes: 'First entry in a three-trade NAS100 setup. The index reclaimed the opening range and held above the consolidation shelf.',
    tradingMistake: 'Did not trail aggressively enough after the first expansion.',
    mindset: 'Patient',
    exitComment: 'Held through the first push and took profit on the second leg.',
    emotions: ['Calm', 'Confident'],
    planAdherence: 'Followed Exactly',
    openTime: '2026-02-12T09:24:00+02:00',
    closeTime: '2026-02-12T10:31:00+02:00',
    setupId: 'demo-nas-momentum',
    setupName: 'NAS100 Momentum Sequence',
  }),
  demoTrade({
    id: 'demo-trade-010',
    pair: 'NAS100',
    assetType: 'Indices',
    date: '2026-02-13',
    time: '09:19',
    session: 'London',
    direction: 'Long',
    entryPrice: 17510,
    exitPrice: 17548,
    stopLoss: 17476,
    takeProfit: 17592,
    lots: 0.5,
    result: 'Win',
    pnl: 195,
    rr: 2.0,
    rating: 4,
    tags: ['Momentum', 'Continuation', 'Cluster'],
    notes: 'Second trade in the NAS100 sequence. A smoother continuation after the initial imbalance was confirmed.',
    tradingMistake: 'Started scaling out before the strongest part of the move.',
    mindset: 'Methodical',
    exitComment: 'Closed into strength after the break of the minor consolidation.',
    emotions: ['Calm', 'Committed'],
    planAdherence: 'Followed Exactly',
    openTime: '2026-02-13T09:19:00+02:00',
    closeTime: '2026-02-13T10:04:00+02:00',
    setupId: 'demo-nas-momentum',
    setupName: 'NAS100 Momentum Sequence',
  }),
  demoTrade({
    id: 'demo-trade-011',
    pair: 'NAS100',
    assetType: 'Indices',
    date: '2026-02-16',
    time: '14:38',
    session: 'New York',
    direction: 'Short',
    entryPrice: 17642,
    exitPrice: 17687,
    stopLoss: 17624,
    takeProfit: 17595,
    lots: 0.4,
    result: 'Loss',
    pnl: -210,
    rr: 2.1,
    rating: 2,
    tags: ['Mean Reversion', 'Late Entry', 'Cluster'],
    notes: 'The third NAS100 trade was weaker and the market was already extended. The short thesis was valid but poorly timed.',
    tradingMistake: 'Entered after the move was already overextended.',
    mindset: 'Overconfident',
    exitComment: 'Stopped out as the index squeezed higher in the New York session.',
    emotions: ['Stubborn', 'Frustrated'],
    planAdherence: 'Minor Deviation',
    openTime: '2026-02-16T14:38:00+02:00',
    closeTime: '2026-02-16T15:11:00+02:00',
    setupId: 'demo-nas-momentum',
    setupName: 'NAS100 Momentum Sequence',
  }),
  demoTrade({
    id: 'demo-trade-012',
    pair: 'EURUSD',
    assetType: 'Forex',
    date: '2026-02-26',
    time: '07:54',
    session: 'London',
    direction: 'Long',
    entryPrice: 1.0765,
    exitPrice: 1.0792,
    stopLoss: 1.0748,
    takeProfit: 1.0818,
    lots: 1.1,
    result: 'Win',
    pnl: 150,
    rr: 1.9,
    rating: 4,
    tags: ['London Open', 'Reclaim', 'Discipline'],
    notes: 'Good reclaim trade after a sweep of the session low. This was a straight execution trade with no drama.',
    tradingMistake: 'Could have added a second unit on the retest, but the read was still solid.',
    mindset: 'Composed',
    exitComment: 'Took a partial at target and closed the rest into the session high.',
    emotions: ['Composed', 'Confident'],
    planAdherence: 'Followed Exactly',
    openTime: '2026-02-26T07:54:00+02:00',
    closeTime: '2026-02-26T09:48:00+02:00',
  }),
  demoTrade({
    id: 'demo-trade-013',
    pair: 'XAUUSD',
    assetType: 'Commodities',
    date: '2026-03-04',
    time: '10:16',
    session: 'London',
    direction: 'Long',
    entryPrice: 2051.3,
    exitPrice: 2048.9,
    stopLoss: 2049.1,
    takeProfit: 2056.8,
    lots: 0.6,
    result: 'Loss',
    pnl: -130,
    rr: 1.7,
    rating: 2,
    tags: ['Failed Base', 'Gold', 'Chop'],
    notes: 'The level was attractive but the market had already lost momentum. This was a low-conviction long in a choppy market.',
    tradingMistake: 'Took the trade because the level looked good, not because momentum supported it.',
    mindset: 'Hopeful',
    exitComment: 'Stopped quickly as price rejected the area again.',
    emotions: ['Hopeful', 'Disappointed'],
    planAdherence: 'Minor Deviation',
    openTime: '2026-03-04T10:16:00+02:00',
    closeTime: '2026-03-04T10:48:00+02:00',
  }),
  demoTrade({
    id: 'demo-trade-014',
    pair: 'USDJPY',
    assetType: 'Forex',
    date: '2026-03-09',
    time: '06:59',
    session: 'Asia',
    direction: 'Short',
    entryPrice: 149.48,
    exitPrice: 149.46,
    stopLoss: 149.88,
    takeProfit: 148.92,
    lots: 0.9,
    result: 'BE',
    pnl: 0,
    rr: 1.8,
    rating: 3,
    tags: ['Asia Fade', 'Breakeven', 'Management'],
    notes: 'The trade reached the initial reaction point but failed to extend. Breakeven was the right outcome after the market hesitated.',
    tradingMistake: 'Did not let the first pullback breathe, but the decision to flatten was still fair.',
    mindset: 'Neutral',
    exitComment: 'Flattened the position after the move stalled around the midpoint.',
    emotions: ['Neutral', 'Disciplined'],
    planAdherence: 'Minor Deviation',
    openTime: '2026-03-08T06:59:00+02:00',
    closeTime: '2026-03-08T07:42:00+02:00',
  }),
  demoTrade({
    id: 'demo-trade-015',
    pair: 'GBPUSD',
    assetType: 'Forex',
    date: '2026-03-13',
    time: '13:04',
    session: 'New York',
    direction: 'Short',
    entryPrice: 1.2821,
    exitPrice: 1.2776,
    stopLoss: 1.2840,
    takeProfit: 1.2758,
    lots: 1.2,
    result: 'Win',
    pnl: 280,
    rr: 2.6,
    rating: 5,
    tags: ['Trend Continuation', 'London High', 'Execution'],
    notes: 'Strong continuation short after London failed to reclaim the highs. This was a textbook trend-day follow-through.',
    tradingMistake: 'Should have taken a partial a bit later to maximize the runner.',
    mindset: 'Focused',
    exitComment: 'Captured a full move and respected the session shift into New York.',
    emotions: ['Focused', 'Patient'],
    planAdherence: 'Followed Exactly',
    openTime: '2026-03-13T13:04:00+02:00',
    closeTime: '2026-03-13T15:36:00+02:00',
  }),
  demoTrade({
    id: 'demo-trade-016',
    pair: 'NAS100',
    assetType: 'Indices',
    date: '2026-03-18',
    time: '09:41',
    session: 'London',
    direction: 'Short',
    entryPrice: 17822,
    exitPrice: 17853,
    stopLoss: 17806,
    takeProfit: 17762,
    lots: 0.5,
    result: 'Loss',
    pnl: -175,
    rr: 1.9,
    rating: 2,
    tags: ['Reversal', 'Weak Session', 'Impulse'],
    notes: 'Took a reversal in the middle of a weak session. The idea was reasonable but the market had no urgency to follow through.',
    tradingMistake: 'Entered before confirming a rejection of the intraday high.',
    mindset: 'Impatient',
    exitComment: 'Stopped out after the market built higher lows instead of rolling over.',
    emotions: ['Impatient', 'Annoyed'],
    planAdherence: 'Major Deviation',
    openTime: '2026-03-18T09:41:00+02:00',
    closeTime: '2026-03-18T10:05:00+02:00',
  }),
  demoTrade({
    id: 'demo-trade-017',
    pair: 'EURUSD',
    assetType: 'Forex',
    date: '2026-03-24',
    time: '08:09',
    session: 'London',
    direction: 'Long',
    entryPrice: 1.0791,
    exitPrice: 1.0829,
    stopLoss: 1.0774,
    takeProfit: 1.0848,
    lots: 1.0,
    result: 'Win',
    pnl: 220,
    rr: 2.3,
    rating: 4,
    tags: ['Reclaim', 'Pullback', 'Plan'],
    notes: 'A measured long after a clean reclaim of the prior session low. Price respected the pullback and held the higher low.',
    tradingMistake: 'Could have trusted the first continuation candle a little more instead of waiting for an extra confirmation.',
    mindset: 'Disciplined',
    exitComment: 'Took gains into the next liquidity pool and closed before the session change.',
    emotions: ['Calm', 'Disciplined'],
    planAdherence: 'Followed Exactly',
    openTime: '2026-03-24T08:09:00+02:00',
    closeTime: '2026-03-24T09:56:00+02:00',
  }),
  demoTrade({
    id: 'demo-trade-018',
    pair: 'US30',
    assetType: 'Indices',
    date: '2026-03-27',
    time: '14:52',
    session: 'New York',
    direction: 'Long',
    entryPrice: 38742,
    exitPrice: 38861,
    stopLoss: 38690,
    takeProfit: 38940,
    lots: 0.4,
    result: 'Win',
    pnl: 360,
    rr: 2.7,
    rating: 5,
    tags: ['Breakout', 'Risk On', 'Weekly Close'],
    notes: 'Strong late-week breakout with broad market participation. The trade aligned with the intraday structure and carried cleanly into the close.',
    tradingMistake: 'Took profits before the very end of the move, although the execution was still high quality.',
    mindset: 'Confident',
    exitComment: 'Managed the move well and booked ahead of the final acceleration.',
    emotions: ['Excited', 'Controlled'],
    planAdherence: 'Followed Exactly',
    openTime: '2026-03-27T14:52:00+02:00',
    closeTime: '2026-03-27T16:18:00+02:00',
  }),
];

export const demoNotes: Note[] = [
  {
    id: 'demo-note-001',
    title: 'January Playbook',
    content: 'Focus on London sweeps, avoid chasing news candles, and wait for confirmation before scaling in.',
    date: '2026-01-04T08:00:00+02:00',
    tags: ['Playbook', 'Process'],
    color: 'YELLOW',
    isPinned: true,
    position: 0,
  },
  {
    id: 'demo-note-002',
    title: 'Mistake Log',
    content: 'Recurring errors: early entries, moving stops to breakeven too quickly, and taking countertrend trades after a sharp move.',
    date: '2026-02-09T17:10:00+02:00',
    tags: ['Psychology', 'Mistakes'],
    color: 'RED',
    isPinned: false,
    position: 1,
  },
  {
    id: 'demo-note-003',
    title: 'Weekly Checklist',
    content: 'Use the higher-time-frame bias, confirm liquidity sweep, wait for displacement, and keep risk consistent.',
    date: '2026-03-10T06:40:00+02:00',
    tags: ['Checklist', 'Execution'],
    color: 'GREEN',
    isPinned: true,
    isList: true,
    listItems: [
      { id: 'demo-note-003-1', text: 'Higher-time-frame bias aligned', checked: true, indentLevel: 0 },
      { id: 'demo-note-003-2', text: 'Liquidity sweep confirmed', checked: true, indentLevel: 0 },
      { id: 'demo-note-003-3', text: 'Displacement candle closed', checked: false, indentLevel: 0 },
    ],
    position: 2,
  },
  {
    id: 'demo-note-004',
    title: 'March Review Table',
    content: 'Summary of March execution and emotion patterns.',
    date: '2026-03-30T19:20:00+02:00',
    tags: ['Review', 'Metrics'],
    color: 'BLUE',
    isPinned: false,
    tableData: {
      rows: [
        [{ text: 'Metric' }, { text: 'Value' }],
        [{ text: 'Win Rate' }, { text: '67%' }],
        [{ text: 'Best Session' }, { text: 'London' }],
      ],
    },
    position: 3,
  },
];

export const demoDailyBias: DailyBias[] = [
  { date: '2026-01-05', bias: 'Bullish', notes: 'Breakout bias after London reclaim.', actualOutcome: 'Aligned' },
  { date: '2026-01-09', bias: 'Bearish', notes: 'Failed to wait for confirmation on a news spike.', actualOutcome: 'Against' },
  { date: '2026-02-12', bias: 'Bullish', notes: 'NAS100 momentum day with clean continuation.', actualOutcome: 'Aligned' },
  { date: '2026-02-16', bias: 'Bullish', notes: 'Too much confidence after a strong run.', actualOutcome: 'Against' },
  { date: '2026-03-13', bias: 'Bearish', notes: 'Trend continuation into New York.', actualOutcome: 'Aligned' },
  { date: '2026-03-18', bias: 'Neutral', notes: 'Choppy conditions, best to reduce size.', actualOutcome: 'Neutral' },
  { date: '2026-03-28', bias: 'Bullish', notes: 'Late-week risk-on move across indices.', actualOutcome: 'Aligned' },
];

export const demoEASession: EASession = {
  id: 'demo-ea-session',
  sync_key: 'real-sync-key',
  last_updated: '2026-03-28T17:02:00+02:00',
  data: {
    account: {
      balance: 12840,
      equity: 13124,
      profit: 284,
      margin: 642,
      margin_level: 204.8,
      company: 'BluePeak Capital',
      login: 441288,
      server: 'BluePeak-Demo',
      is_demo: true,
      currency: 'USD',
      leverage: 100,
    },
    openPositions: [
      {
        ticket: 9011201,
        symbol: 'EURUSD',
        volume: 0.6,
        type: 'BUY',
        open_price: 1.0831,
        current_price: 1.0846,
        profit: 89,
        comment: 'Runner from London reclaim',
        time: 1774714920,
      },
      {
        ticket: 9011202,
        symbol: 'XAUUSD',
        volume: 0.3,
        type: 'SELL',
        open_price: 2048.4,
        current_price: 2044.9,
        profit: 195,
        comment: 'Partial position from the sweep setup',
        time: 1774718220,
      },
    ],
    trades: [],
    isHeartbeat: true,
  },
};

export const getDemoProfile = (baseProfile: UserProfile | null): UserProfile => {
  const fallbackName = baseProfile?.name || 'Demo Trader';
  const fallbackCountry = baseProfile?.country || 'South Africa';

  return {
    name: fallbackName,
    country: fallbackCountry,
    accountName: 'Sample Trading Account',
    initialBalance: 12500,
    currency: 'USD',
    currencySymbol: '$',
    syncMethod: 'EA_CONNECT',
    experienceLevel: baseProfile?.experienceLevel || 'Intermediate',
    tradingStyle: baseProfile?.tradingStyle || 'Day Trader',
    onboarded: true,
    plan: 'PRO TIER (ANALYSTS)',
    syncKey: 'real-sync-key',
    eaConnected: true,
    autoJournal: true,
    avatarUrl: baseProfile?.avatarUrl,
    themePreference: baseProfile?.themePreference || 'obsidian',
    chartLayout: baseProfile?.chartLayout,
    chartConfigCharts: baseProfile?.chartConfigCharts,
    chartConfig: baseProfile?.chartConfig,
    keepChartsAlive: baseProfile?.keepChartsAlive,
    defaultRR: baseProfile?.defaultRR,
  };
};
